name: "ci"
run-name: "build & test"

on: [push]

env:
  GH_TOKEN: ${{github.token}}

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: |
          apt update -y
          apt install -y rustc
          apt install -y make
      - name: "Build"
        run: make translator
      - name: "Test"
        run: make test
