name: "ci"
run-name: "build & test"

on: [push]

env:
  GH_TOKEN: ${{github.token}}
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          apt update
          apt install cmake -y
      - name: "Build"
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: "Unit Test"
        run: # TODO:
      - name: "Golden Test"
        run: # TODO:
