name: "ci"
run-name: "build & test"

on: [push]

env:
  GH_TOKEN: ${{github.token}}
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - name: "Prep"
        run: |
          - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: "Build"
        run: cargo build
      - name: "Test"
        run: cargo test
